
# Step 1: Use Node.js base image
FROM node:20-bullseye

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Pass build args (values come from docker-compose)
ARG GOOGLE_API_KEY
ARG JWT_SECRET
ARG NEXT_PUBLIC_BASE_URL
ARG TAVILY_API_KEY
ARG MONGO_URI

ENV GOOGLE_API_KEY=$GOOGLE_API_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV TAVILY_API_KEY=$TAVILY_API_KEY
ENV MONGO_URI=$MONGO_URI

RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
